/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package librent;

import java.math.BigInteger;
import java.time.Instant;

public class Library {
    
    public final BigInteger rent = BigInteger.valueOf(2).pow(10);
    //final public BigInteger rent = new BigInteger("1024");

    public String getGreeting() {
        int i = 2<<4;
        long unixTimestamp = Instant.now().getEpochSecond();
        return ("Hello world " + i + " and square root of unix timestamp " + Math.sqrt(unixTimestamp) + "\n");
    }    
        
    public boolean someLibraryMethod() {
        return false;
    }

    public BigInteger returnRent() { return rent;}
}
